name: 🚀 🚀 🚀 Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ ✅ ✅ Deploying to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          key: ${{secrets.KEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          port: ${{secrets.PORT}}
          script: |
            ${{secrets.SCRIPT}}


